name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        run: yarn prisma generate

      - name: Run ESLint
        run: yarn lint

      - name: Run type check
        run: yarn typecheck

      - name: Check formatting
        run: yarn format:check

  build:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        run: yarn prisma generate

      - name: Build application
        run: yarn build
        env:
          # Mock environment variables for build
          AUTH_SECRET: "mock-secret-for-build"
          DATABASE_URL: "postgresql://mock:mock@localhost:5432/mock"
          REPLICATE_API_TOKEN: "mock-token"
          AUTH_DISCORD_ID: "mock-id"
          AUTH_DISCORD_SECRET: "mock-secret"
          SKIP_ENV_VALIDATION: "true"
